server:
  port: 9999
  contextPath: /

spring:
  profiles.active: local
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: false
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect

  datasource:
    url: jdbc:mysql://localhost:3306/migration?characterEncoding=utf8&useUnicode=true&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: "password"
    driver-class-name: com.mysql.jdbc.Driver

data.path: data
